---
- name: Install node and npm
  hosts: webserver
  vars_files:
    - project-vars
  #  vars:
  #    - version: 0.1.0
  #    - destination: /home/ubuntu
  tasks:
    - name: Update apt repo and cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
    - name: Install node and npm
      become: yes
      apt:
        pkg:
          - nodejs
          - npm
    - name: Create new linux user for nodejs app
      become: yes
      user:
        name: nodejs
        comment: Nodejs user
        group: admin
        shell: /bin/bash
        state: present
      register: user_creation_result
    - debug:
        msg: "{{ user_creation_result }}"
    - name: Copy nodejs folder to a server
      become: yes
      copy:
        src: my-app-{{version}}.tgz
        dest: "{{destination}}/app-{{version}}.tgz"
    - name: Unpack nodejs file
      become: yes
      unarchive:
        src: "{{destination}}/app-{{version}}.tgz"
        dest: "{{destination}}"
        remote_src: yes
    - name: Install nodejs dependencies
      become: yes
      npm:
        path: "{{destination}}/package"
        state: present
    - name: Start nodejs app
      command:
        chdir: "{{ destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure nodejs app is running
      become: yes
      shell: ps aux | grep node | grep -v grep
      register: app_status
    - debug:
        msg: "{{ app_status.stdout_lines }}"
